// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Files Uploader Service",
    "version": "1"
  },
  "paths": {
    "/upload": {
      "post": {
        "summary": "upload",
        "description": "",
        "operationId": "upload.post.upload",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "schemes": [
    "https"
  ]
};